Add active users checksum, probably does not compile
KMSUJ/lada pull request #22
Opened 2020-10-13 16:41 UTC by koostosh

code is pretty much self-explainatory, however i have no fraking idea how SQLAlchemy + Flask works, so it will need corrections. 

Checksum needs to be printed on results page later.

2020-10-13 17:11 UTC, koostosh commented
compiles now. Needs some testing anyway

2020-10-15 06:17 UTC, Larhard requested changes

2020-10-15 11:04 UTC, orhid commented on lada/dike/maintenance.py
> +            return
Jak funkcja nie zwróci czegoś rozsądnego, to program posypie się dalej i zamiast flasha z komunikatem, dostaniesz error na serwerze.

2020-10-15 11:11 UTC, orhid commented on lada/fellow/forms.py
> +    active = SubmitField('Lista aktywnych')
A ja nawet wyrzuciłbym to stąd. Można zrobić osobny route, który będzie ci wyświetlał tę checksumę. Wtedy nie robisz bałaganu w panelu, jak chcesz to mieć tam, to zamień ten submit guzik na ogniwo po prostu.

2020-10-15 11:14 UTC, orhid commented on lada/templates/fellow/panel.html
> +    {{ checksum }}
jeśli właśnie nie nacisnąłeś tego submita, który to liczy, to strona się nie wyrenderuje, bo wtedy nie podajesz do rendera zmiennej checksum.

2020-10-15 11:16 UTC, orhid commented on lada/templates/dike/reckoning.html
> +    {{ checksum }}
Można to wrzucić w komentarzu, wtedy będzie widoczne w źródle strony, jakby ktoś był ciekawy, a nie będzie trzeba myśleć, jak to ładnie wyświetlać.

2020-10-15 11:18 UTC, orhid reviewed
Trochę uważam, że ta checksuma bardziej komplikuje rzeczy, niż zabezpiecza głosowanie.

2020-10-15 15:27 UTC, Larhard commented on lada/templates/fellow/panel.html
> +    {{ checksum }}
wyrenderuje, on ignoruje takie rzeczy

2020-10-15 15:28 UTC, Larhard commented
On #23

2020-10-15 15:28 UTC, closed without merging