split election stages
KMSUJ/lada pull request #28
Opened 2020-10-31 17:58 UTC by orhid

opcja bez niszczenia rejectów, wciąż nie przechodzi jeden test, ale nie do końca wiem, jak to naprawić, bo trzeba je chyba napisać od nowa dla wyborów w kilku fazacyh

2020-10-31 18:05 UTC, orhid commented
do tego na bank wybieranie kandydatów podczas reckoningu zarządu nie działa, to pzostaje do naprawienia

2020-11-03 21:28 UTC, Larhard requested changes
Głównie to `t` blokuje approva.

Dorzuciłem 2 poprawki, które mi się rzuciły w oczy, ale w High, nie Critical, bo da się bez tego żyć
![image](https://user-images.githubusercontent.com/4514187/98042418-d6b7f200-1e23-11eb-85e2-c18f12482105.png)

2020-11-03 21:28 UTC, Larhard commented on lada/dike/maintenance.py
>          log.warning(f"Legal voter detected: {voter}")
It seems I forgot to remove this "warning"? It should be at most debug. I will fix it if you won't.

2020-11-03 21:28 UTC, Larhard commented on t
> +    tests.utils.web_dike_begin_voting(client)
What is "t"? It seems like some temporary file which should not be here

2020-11-03 22:08 UTC, orhid commented on t
> +    tests.utils.web_dike_begin_voting(client)
True, my bad, forgot to delete

2020-11-03 22:09 UTC, orhid commented on lada/dike/maintenance.py
> +        if election.is_stage(STAGE_COVISION):
Ah, dunno why I did that, twas a long day

2020-11-07 17:29 UTC, Larhard approved these changes

2020-11-07 17:29 UTC, Larhard commented on lada/dike/stv/candidate.py
> +    def shortest_score(self):
używasz tego jeszcze?

2020-11-07 17:29 UTC, Larhard commented on lada/dike/stv/candidate.py
> +        for i in range(max(len(self.score[-1]), len(other.score[-1]))):
tego maxa wstawiłem trochę pseudokodowo. Co się stanie, gdy długości będą różne?

2020-11-07 17:29 UTC, Larhard commented on lada/dike/stv/candidate.py
> +        for i in range(max(len(self.score[-1]), len(other.score[-1]))):
ew. możesz zostawić, bo i tak tu grzebnę przy rebasie

2020-11-07 17:39 UTC, merged